### ISSUE TITLE
Лаба 1

### ISSUE THREAD

**Issue by irinamatveeva** [katuuushka/bd_labs#1]
Нужно изменить структуру репозитория и имя. А то сейчас файлы с заданиями лаб 1 и 2 лежат в репозитории с именем лаба 1. Лучше репозиторий назвать BD labs, а внутри папки для каждой лабы

**Comment by irinamatveeva** [comment]
Лаба 1 недоделана

**Comment by lasbio** [comment]
Лаб. 1 зачтена с замечаниями. Прошу начиная с лаб 3 всегда создавать директорию по каждую лабораторную. Если это не будет выполняться, то лабораторная не будет проверяться, т.е. лабораторная будет считаться невыполненной.
