### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [katuuushka/bd_labs#2]
Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть SELECT ... FROM.... 
Задание 2 - нужно отобразить и названия объектов тоже
Задание 3 и 4 (и далее) - бесплатно для членов клуба, а не гостей
Задание 5 - условие "не превышающий", то есть <= , а не <. Также в выборку попадут и бесплатные объекты, а так не должно быть.
Задание 6 - неправильно
Задание 7 - использование IN это очень хорошо, но есть недочет: когда просят вывести "объекты", лучше не выводить лишние все остальные данные
Задание 8 - не выполнено, нет столбца качественной стоимости со значениями "дорогой" и "дешевый".
Задание 9 - не работает, выбираются пользователи, зарегистрированные и ранее. Также не нужно выводить все данные пользователей, достаточно фамилии, имени и memid.
Задание 11 - Задание 11 - как различить какой ряд в возвращаемом результате относится к member, а какой к facility?
Задание 12 - зачем limit 1?
Задание 13 - а если вчера еще один зарегистрировался? тогда дата уже не верная. Надо по-другому реализовать алгоритм.
Задание 14 - условия заданы не верно, мы не знаем цифр 5 и 80.

**Comment by katuuushka** [comment]
все ошибки исправлены
